package com.kissaki.rhinoforgwt;

public interface Kissaki_CodeTag {
	
	
	String CODE_TO_BOOLEAN = "toBoolean",
	CODE_TONUMBER = "toNumber",
	CODE_WRAP_DOUBLE = "wrapDouble",
	CODE_WRAP_REGEXP = "wrapRegExp",
	CODE_TYPEOF = "typeof",
	CODE_SHALLOWEQ = "shallowEq",
	CODE_NAME = "name",
	CODE_GETPROPFUNCTIONANDTHIS = "getPropFunctionAndThis",
	CODE_LASTSTOREDSCRIPTABLE = "lastStoredScriptable",
	CODE_INITSCRIPT = "initScript",
	CODE_GETVALUEFUNCTIONANDTHIS = "getValueFunctionAndThis",
	CODE_CREATEFUNCTIONACTUIVATION = "createFunctionActivation",
	CODE_ENTERFUNCTIONACTUIVATION = "enterActivationFunction",
	CODE_EXITFUNCTIONACTUIVATION = "exitActivationFunction",
	CODE_SETOBJECT_PROP = "setObjectProp",
	CODE_NEWOBJECTLITERAL = "newObjectLiteral",
	CODE_TOBOOLEAN = "toBoolean",
	CODE_SETNAME = "setName",
	CODE_BIND = "bind",
	CODE_GETOBJECTELEM = "getObjectElem",
	CODE_GETOBJECTPROPNOWARN = "getObjectPropNoWarn",
	CODE_GETOBJECTPROP = "getObjectProp",
	CODE_SHALLOW_EQ = "shallowEq",
	CODE_PADARGUMENTS = "padArguments",
	CODE_CMPLE =  "cmp_LE",
	CODE_CMPLT = "cmp_LT",
	CODE_SETPBJECTELEM = "setObjectElem",
	CODE_GETNAMEFUNCTIONANDTHIS = "getNameFunctionAndThis",
	CODE_TYPEOFNAME = "typeofName",
	CODE_NEWOBJECT = "newObject",
	CODE_NAMEINCRDECR = "nameIncrDecr",
	CODE_NEWCATCHSCOPE = "newCatchScope",
	CODE_ENTERWITH = "enterWith",
	CODE_LEAVEWITH = "leaveWith",
	CODE_LATEST = "latest",
	CODE_ENUMID = "enumId",
	CODE_ENUMINIT = "enumInit",
	CODE_ENUMNEXT = "enumNext",
	CODE_EQ = "eq",
	CODE_GETELEMFUNCTIONANDTHIS = "getElemFunctionAndThis",
	CODE_TOINT32 = "toInt32",
	CODE_PROPINCRDECR = "propIncrDecr",
	CODE_DELETE = "delete",
	CODE_TOUINT32 = "toUint32",
	CODE_INSTANCEOF = "instanceOf",
	CODE_ADDINSTRUCTIONCOUNT = "addInstructionCount",
	CODE_ENTERDOTQUERY = "enterDotQuery",
	CODE_CALLREF = "callRef",
	CODE_GETOBJECTINDEX = "getObjectIndex",
	CODE_ELEMINCRDECR = "elemIncrDecr",
	CODE_REFINCRDECR = "refIncrDecr",
	CODE_REFSET = "refSet",
	CODE_REFDEL = "refDel",
	CODE_REFGET = "refGet",
	CODE_SPECIALREF = "specialRef",
	CODE_ESCAPEATTRIBUTEVALUE = "escapeAttributeValue",
	CODE_ESCAPETEXTVALUE = "escapeTextValue",
	CODE_SETDEFAULTNAMESPACE = "setDefaultNamespace",
	CODE_WRAPINT = "wrapInt",
	CODE_SETCONST = "setConst",
	CODE_SETOBJECTINDEX = "setObjectIndex",
	CODE_SETOBJECTPROP = "setObjectProp",
	CODE_LEAVEDOTQUERY = "leaveDotQuery",
	CODE_UPDATEDOTQUERY = "updateDotQuery",
	CODE_ADD = "add",
	CODE_CLASSDEF_STRING = ")Ljava/lang/String;",
	CODE_IN = "in";
	
}
